import { Megaphone } from "lucide-react";

export const nav_items = [
  {
    id: 1,
    label: "Discover",
    path: "/discover",
  },
  // { id: 2, label: "find jobs", path: "/find_jobs" },
  // { id: 4, label: "employers", path: "/employers" },
  { id: 6, label: "For job seekers", path: "/candidates/overview" },
  {
    id: 5,
    label: "For companies",
    path: "/recruit/overview",
  },
];

export const popular_job_categories_data = [
  {
    icon: "ri-money-dollar-circle-line",
    categories: "Accounting / Finance",
    open_positions: "2",
  },
  {
    icon: "ri-paint-brush-line",
    categories: "Design",
    open_positions: "42",
  },
  {
    icon: "ri-code-box-line",
    categories: "Development",
    open_positions: "12",
  },
  {
    icon: "ri-booklet-line",
    categories: "Human Resource",
    open_positions: "12",
  },
  {
    icon: "ri-flight-takeoff-line",
    categories: "Automotive Jobs",
    open_positions: "2",
  },
  {
    icon: "ri-money-dollar-circle-line",
    categories: "Customer Service",
    open_positions: "2",
  },
  {
    icon: "ri-money-dollar-circle-line",
    categories: "Health and Care",
    open_positions: "25",
  },
  {
    icon: "ri-briefcase-4-line",
    categories: "Health and Care",
    open_positions: "25",
  },
  {
    icon: "ri-caravan-fill",
    categories: "Project Management",
    open_positions: "92",
  },
];

export const featured_jobs = [
  {
    image: "1-1.webp",
    job_title: "Software Engineer (Android), Libraries",
    company: "Segment",
    location: "London, UK",
    posted_time: "11 hours ago",
    salary_range: "$35k - $45k",
    employment_type: "Full Time",
    visibility: "Private",
    urgency: "Urgent",
  },
  {
    image: "1-1.webp",
    job_title: "Recruiting Coordinator",
    company: "Catalyst",
    location: "London, UK",
    posted_time: "11 hours ago",
    salary_range: "$35k - $45k",
    employment_type: "Full Time",
    visibility: "Private",
    urgency: "Urgent",
  },
  {
    image: "1-1.webp",
    job_title: "Product Manager, Studio",
    company: "Invision",
    location: "London, UK",
    posted_time: "11 hours ago",
    salary_range: "$35k - $45k",
    employment_type: "Full Time",
    visibility: "Private",
    urgency: "Urgent",
  },
  {
    image: "1-1.webp",
    job_title: "Senior Product Designer",
    company: "Upwork",
    location: "London, UK",
    posted_time: "11 hours ago",
    salary_range: "$35k - $45k",
    employment_type: "Full Time",
    visibility: "Private",
    urgency: "Urgent",
  },
  {
    image: "1-1.webp",
    job_title: "Senior Full Stack Engineer, Creator Success",
    company: "Medium",
    location: "London, UK",
    posted_time: "11 hours ago",
    salary_range: "$35k - $45k",
    employment_type: "Full Time",
    visibility: "Private",
    urgency: "Urgent",
  },
  {
    image: "1-1.webp",
    job_title: "Software Engineer (Android), Libraries",
    company: "Figma",
    location: "London, UK",
    posted_time: "11 hours ago",
    salary_range: "$35k - $45k",
    employment_type: "Full Time",
    visibility: "Private",
    urgency: "Urgent",
  },
];

export const story_blog = [
  {
    title: "Cool Features Added!",
    date_published: "11 January 2023",
    author: "John Doe",
    category: "Technology",
    tags: ["Cool Features", "Software Development", "Android", "Libraries"],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    featured_image: "story01.png",
    share_count: 150,
    comments: [
      {
        user: "Alice",
        comment: "Great additions! Can't wait to try them out.",
      },
      {
        user: "Bob",
        comment: "Impressive work! Keep it up.",
      },
    ],
  },
  {
    title: "Top rated app! Yupp.",
    date_published: "11 January 2023",
    author: "John Doe",
    category: "Technology",
    tags: ["Cool Features", "Software Development", "Android", "Libraries"],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    featured_image: "story02.png",
    share_count: 150,
    comments: [
      {
        user: "Alice",
        comment: "Great additions! Can't wait to try them out.",
      },
      {
        user: "Bob",
        comment: "Impressive work! Keep it up.",
      },
    ],
  },
  {
    title: "Creative ideas on app.",
    date_published: "11 January 2023",
    author: "John Doe",
    category: "Technology",
    tags: ["Cool Features", "Software Development", "Android", "Libraries"],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    featured_image: "story03.png",
    share_count: 150,
    comments: [
      {
        user: "Alice",
        comment: "Great additions! Can't wait to try them out.",
      },
      {
        user: "Bob",
        comment: "Impressive work! Keep it up.",
      },
    ],
  },
];

export const client_reviews = [
  {
    review_title: "Great quality!",
    review:
      "Without JobHunt i’d be homeless, they found me a job and got me orted out quickly with everything! Can’t quite… The Mitech teamworks really hard to ensure high level of quality",
    user: {
      name: " John Doe",
      title: "designer",
      image: "testi-thumb-2.webp",
    },
  },
  {
    review_title: "Great quality!",
    review:
      "Without JobHunt i’d be homeless, they found me a job and got me orted out quickly with everything! Can’t quite… The Mitech teamworks really hard to ensure high level of quality",
    user: {
      name: " John Doe",
      title: "designer",
      image: "testi-thumb-2.webp",
    },
  },
  {
    review_title: "Great quality!",
    review:
      "Without JobHunt i’d be homeless, they found me a job and got me orted out quickly with everything! Can’t quite… The Mitech teamworks really hard to ensure high level of quality",
    user: {
      name: " John Doe",
      title: "designer",
      image: "testi-thumb-2.webp",
    },
  },
  {
    review_title: "Great quality!",
    review:
      "Without JobHunt i’d be homeless, they found me a job and got me orted out quickly with everything! Can’t quite… The Mitech teamworks really hard to ensure high level of quality",
    user: {
      name: " John Doe",
      title: "designer",
      image: "testi-thumb-2.webp",
    },
  },
  {
    review_title: "Great quality!",
    review:
      "Without JobHunt i’d be homeless, they found me a job and got me orted out quickly with everything! Can’t quite… The Mitech teamworks really hard to ensure high level of quality",
    user: {
      name: " John Doe",
      title: "designer",
      image: "testi-thumb-2.webp",
    },
  },
  {
    review_title: "Great quality!",
    review:
      "Without JobHunt i’d be homeless, they found me a job and got me orted out quickly with everything! Can’t quite… The Mitech teamworks really hard to ensure high level of quality",
    user: {
      name: " John Doe",
      title: "designer",
      image: "testi-thumb-2.webp",
    },
  },
  {
    review_title: "Great quality!",
    review:
      "Without JobHunt i’d be homeless, they found me a job and got me orted out quickly with everything! Can’t quite… The Mitech teamworks really hard to ensure high level of quality",
    user: {
      name: " John Doe",
      title: "designer",
      image: "testi-thumb-2.webp",
    },
  },
  {
    review_title: "Great quality!",
    review:
      "Without JobHunt i’d be homeless, they found me a job and got me orted out quickly with everything! Can’t quite… The Mitech teamworks really hard to ensure high level of quality",
    user: {
      name: " John Doe",
      title: "designer",
      image: "testi-thumb-2.webp",
    },
  },
  {
    review_title: "Great quality!",
    review:
      "Without JobHunt i’d be homeless, they found me a job and got me orted out quickly with everything! Can’t quite… The Mitech teamworks really hard to ensure high level of quality",
    user: {
      name: " John Doe",
      title: "designer",
      image: "testi-thumb-2.webp",
    },
  },
  {
    review_title: "Great quality!",
    review:
      "Without JobHunt i’d be homeless, they found me a job and got me orted out quickly with everything! Can’t quite… The Mitech teamworks really hard to ensure high level of quality",
    user: {
      name: " John Doe",
      title: "designer",
      image: "testi-thumb-2.webp",
    },
  },
  {
    review_title: "Great quality!",
    review:
      "Without JobHunt i’d be homeless, they found me a job and got me orted out quickly with everything! Can’t quite… The Mitech teamworks really hard to ensure high level of quality",
    user: {
      name: " John Doe",
      title: "designer",
      image: "testi-thumb-2.webp",
    },
  },
];

export const job_type_data = [
  { id: 1, label: "Freelancer", value: "freelancer" },
  { id: 2, label: "Full Time", value: "full time" },
  { id: 3, label: "Part Time", value: "part time" },
  { id: 4, label: "Temporary", value: "temporary" },
];
export const date_posted_data = [
  { id: 1, label: "All", value: "all" },
  { id: 2, label: "Last Hour", value: "last hour" },
  { id: 3, label: "Last 24 Hour", value: "last 24 hour" },
  { id: 4, label: "Last 7 Days", value: "last 7 days" },
  { id: 4, label: "Last 14 Days", value: "last 14 days" },
  { id: 4, label: "Last 30 Days", value: "last 30 days" },
];
export const experience_level_data = [
  { id: 1, label: "Fresh", value: "fresh" },
  { id: 2, label: "1 Year", value: "1 year" },
  { id: 3, label: "2 Year", value: "2 year" },
  { id: 4, label: "3 Year", value: "3 year" },
  { id: 4, label: "4 Year", value: "4 year" },
];
export const tags_data = [
  "app",
  "Administrative",
  "Android",
  "Wordpress",
  "Design",
  "React",
];

export const job_categories = [
  "Information Technology (IT) and Software Development",
  "Web Development and Design",
  "Mobile App Development",
  "Frontend Development",
  "Backend Development",
  "Full-stack Development",
  "UI/UX Design",
  "Graphic Design and Multimedia",
  "Game Development",
  "DevOps Engineering",
  "Cloud Computing and Architecture",
  "Database Administration and Management",
  "System Administration",
  "Network Engineering and Administration",
  "Cybersecurity Analysis and Management",
  "IT Support and Helpdesk",
  "Software Quality Assurance and Testing",
  "Artificial Intelligence (AI) and Machine Learning (ML)",
  "Data Engineering and Analytics",
  "Blockchain Development",
  "Embedded Systems Development",
  "Enterprise Resource Planning (ERP) Implementation",
  "IT Consulting and Strategy",
  "IT Project Management",
  "Technical Writing and Documentation",
  "Automation Testing",
  "Augmented Reality (AR) and Virtual Reality (VR) Development",
  "Digital Signal Processing",
  "Information Systems Management",
  "IT Sales and Marketing",
  "IT Training and Education",
  "Mobile and Web UI/UX Design",
  "Motion Graphics Design",
  "Interaction Design",
  "Product Design",
  "User Research and Testing",
  "Visual Design",
  "3D Modeling and Animation",
  "Video Editing and Production",
  "Audio Production and Editing",
  "Creative Direction",
  "Web Content Management",
  "SEO (Search Engine Optimization) Management",
  "E-commerce Development and Management",
  "Content Management System (CMS) Development",
  "User Interface (UI) Development",
  "User Experience (UX) Development",
  "Software Development Lifecycle (SDLC) Management",
  "Responsive Web Design",
  "Mobile Application Design and Development",
];

export const skills = [
  { label: "Adobe Photoshop", value: "Adobe Photoshop" },
  { label: "Adobe Illustrator", value: "Adobe Illustrator" },
  { label: "JavaScript", value: "JavaScript" },
  { label: "Python", value: "Python" },
  { label: "Java", value: "Java" },
  { label: "HTML", value: "HTML" },
  { label: "CSS", value: "CSS" },
  { label: "SQL", value: "SQL" },
  { label: "React.js", value: "React.js" },
  { label: "Node.js", value: "Node.js" },
  { label: "AngularJS", value: "AngularJS" },
  { label: "Vue.js", value: "Vue.js" },
  { label: "C++", value: "C++" },
  { label: "C#", value: "C#" },
  { label: "Ruby", value: "Ruby" },
  { label: "Swift", value: "Swift" },
  { label: "Kotlin", value: "Kotlin" },
  { label: "PHP", value: "PHP" },
  { label: "TypeScript", value: "TypeScript" },
  { label: "R", value: "R" },
  { label: "Machine Learning", value: "Machine Learning" },
  { label: "Data Science", value: "Data Science" },
  { label: "Deep Learning", value: "Deep Learning" },
  { label: "Computer Vision", value: "Computer Vision" },
  {
    label: "Natural Language Processing",
    value: "Natural Language Processing",
  },
  { label: "Blockchain", value: "Blockchain" },
  { label: "Cybersecurity", value: "Cybersecurity" },
  { label: "Cloud Computing", value: "Cloud Computing" },
  { label: "Big Data", value: "Big Data" },
  { label: "Artificial Intelligence", value: "Artificial Intelligence" },
  { label: "Internet of Things (IoT)", value: "Internet of Things (IoT)" },
  { label: "Augmented Reality", value: "Augmented Reality" },
  { label: "Virtual Reality", value: "Virtual Reality" },
  { label: "Web Development", value: "Web Development" },
  { label: "Mobile Development", value: "Mobile Development" },
  { label: "Game Development", value: "Game Development" },
  { label: "UI/UX Design", value: "UI/UX Design" },
  { label: "Graphic Design", value: "Graphic Design" },
  { label: "Product Management", value: "Product Management" },
  { label: "Project Management", value: "Project Management" },
  { label: "Agile Methodologies", value: "Agile Methodologies" },
  { label: "Scrum", value: "Scrum" },
  { label: "Kanban", value: "Kanban" },
  { label: "Lean Management", value: "Lean Management" },
  { label: "DevOps", value: "DevOps" },
  { label: "Continuous Integration", value: "Continuous Integration" },
  { label: "Continuous Deployment", value: "Continuous Deployment" },
  { label: "Git", value: "Git" },
  { label: "GitHub", value: "GitHub" },
  { label: "Bitbucket", value: "Bitbucket" },
  { label: "Jira", value: "Jira" },
  { label: "Confluence", value: "Confluence" },
  { label: "Slack", value: "Slack" },
  { label: "Microsoft Office", value: "Microsoft Office" },
  { label: "Google Workspace", value: "Google Workspace" },
  { label: "Photoshop", value: "Photoshop" },
  { label: "Illustrator", value: "Illustrator" },
  { label: "InDesign", value: "InDesign" },
  { label: "Premiere Pro", value: "Premiere Pro" },
  { label: "After Effects", value: "After Effects" },
  { label: "Final Cut Pro", value: "Final Cut Pro" },
  { label: "Logic Pro", value: "Logic Pro" },
  { label: "Pro Tools", value: "Pro Tools" },
  { label: "Maya", value: "Maya" },
  { label: "Blender", value: "Blender" },
  { label: "ZBrush", value: "ZBrush" },
  { label: "Unity", value: "Unity" },
  { label: "Unreal Engine", value: "Unreal Engine" },
  { label: "3ds Max", value: "3ds Max" },
  { label: "Sketch", value: "Sketch" },
  { label: "Figma", value: "Figma" },
  { label: "Adobe XD", value: "Adobe XD" },
  { label: "Zeplin", value: "Zeplin" },
  { label: "InVision", value: "InVision" },
  { label: "Axure RP", value: "Axure RP" },
  { label: "Framer", value: "Framer" },
  { label: "Marvel", value: "Marvel" },
  { label: "Principle", value: "Principle" },
  { label: "Origami Studio", value: "Origami Studio" },
  { label: "Balsamiq", value: "Balsamiq" },
  { label: "Mockplus", value: "Mockplus" },
  { label: "Adobe After Effects", value: "Adobe After Effects" },
  { label: "Autodesk Maya", value: "Autodesk Maya" },
  { label: "Autodesk 3ds Max", value: "Autodesk 3ds Max" },
  { label: "Blender 3D", value: "Blender 3D" },
  { label: "Unity 3D", value: "Unity 3D" },
  { label: "Unreal Engine 4", value: "Unreal Engine 4" },
  { label: "Sketch App", value: "Sketch App" },
  { label: "Figma Design", value: "Figma Design" },
  { label: "InVision Studio", value: "InVision Studio" },
  { label: "Zeplin Tool", value: "Zeplin Tool" },
  { label: "Adobe Creative Suite", value: "Adobe Creative Suite" },
  { label: "Sketching", value: "Sketching" },
  { label: "Wireframing", value: "Wireframing" },
  { label: "Prototyping", value: "Prototyping" },
  { label: "User Testing", value: "User Testing" },
  { label: "Usability Testing", value: "Usability Testing" },
  { label: "A/B Testing", value: "A/B Testing" },
  { label: "User Research", value: "User Research" },
  { label: "User Experience Design", value: "User Experience Design" },
  { label: "User Interface Design", value: "User Interface Design" },
  { label: "Product Design", value: "Product Design" },
  { label: "Graphic Designing", value: "Graphic Designing" },
  { label: "Motion Graphics", value: "Motion Graphics" },
  { label: "Video Editing", value: "Video Editing" },
  { label: "Audio Editing", value: "Audio Editing" },
  { label: "Sound Design", value: "Sound Design" },
  { label: "Music Production", value: "Music Production" },
  { label: "3D Modeling", value: "3D Modeling" },
  { label: "Animation", value: "Animation" },
  { label: "Game Design", value: "Game Design" },
  { label: "UI Design", value: "UI Design" },
  { label: "UX Design", value: "UX Design" },
  { label: "Wireframes", value: "Wireframes" },
  { label: "Information Architecture", value: "Information Architecture" },
  { label: "Interaction Design", value: "Interaction Design" },
  { label: "Visual Design", value: "Visual Design" },
  { label: "Front-end Development", value: "Front-end Development" },
  { label: "Back-end Development", value: "Back-end Development" },
  { label: "Full-stack Development", value: "Full-stack Development" },
  { label: "Responsive Web Design", value: "Responsive Web Design" },
  { label: "Web Accessibility", value: "Web Accessibility" },
  {
    label: "Cross-browser Compatibility",
    value: "Cross-browser Compatibility",
  },
  { label: "RESTful APIs", value: "RESTful APIs" },
  { label: "GraphQL", value: "GraphQL" },
  { label: "Microservices Architecture", value: "Microservices Architecture" },
  { label: "Serverless Architecture", value: "Serverless Architecture" },
  { label: "Containerization", value: "Containerization" },
  { label: "Docker", value: "Docker" },
  { label: "Kubernetes", value: "Kubernetes" },
  { label: "Amazon Web Services (AWS)", value: "Amazon Web Services (AWS)" },
  { label: "Microsoft Azure", value: "Microsoft Azure" },
  {
    label: "Google Cloud Platform (GCP)",
    value: "Google Cloud Platform (GCP)",
  },
  { label: "Firebase", value: "Firebase" },
  { label: "Heroku", value: "Heroku" },
  { label: "Netlify", value: "Netlify" },
  { label: "DigitalOcean", value: "DigitalOcean" },
  { label: "Linux", value: "Linux" },
  { label: "Unix", value: "Unix" },
  { label: "Windows", value: "Windows" },
  { label: "macOS", value: "macOS" },
  { label: "iOS", value: "iOS" },
  { label: "Android", value: "Android" },
  { label: "Cross-platform Development", value: "Cross-platform Development" },
  { label: "Native Development", value: "Native Development" },
  { label: "Hybrid Development", value: "Hybrid Development" },
  { label: "Flutter", value: "Flutter" },
  { label: "React Native", value: "React Native" },
  { label: "Ionic", value: "Ionic" },
  { label: "Xamarin", value: "Xamarin" },
];

export const job_profile = [
  "Web Developer",
  "Graphic Designer",
  "Video Editor",
  "Content Writer",
  "Social Media Manager",
  "SEO Specialist",
  "Virtual Assistant",
  "Logo Designer",
  "Copywriter",
  "Illustrator",
  "Voiceover Artist",
  "Animator",
  "UI/UX Designer",
  "WordPress Developer",
  "Translator",
  "Transcriptionist",
  "Data Entry Specialist",
  "App Developer",
  "3D Modeler",
  "Music Producer",
  "Game Developer",
  "Ebook Writer",
  "Scriptwriter",
  "Proofreader",
  "Photographer",
  "Digital Marketer",
  "Podcast Editor",
  "Presentation Designer",
  "Resume Writer",
  "Email Marketer",
  "Market Researcher",
  "Infographic Designer",
  "T-Shirt Designer",
  "Whiteboard Animator",
  "Cartoonist",
  "Photo Retoucher",
  "Brand Strategist",
  "Business Card Designer",
  "Video Producer",
  "Audio Engineer",
  "Financial Analyst",
  "Legal Writer",
  "Book Cover Designer",
  "Voice Actor",
  "Social Media Influencer",
  "Video Ad Creator",
  "Mobile App Designer",
  "Database Administrator",
  "Virtual Event Planner",
  "UI Tester",
  "Video Game Tester",
  "Game Designer",
  "Product Photographer",
  "Voice Coach",
  "Script Editor",
  "Business Plan Writer",
  "Financial Planner",
  "Tax Consultant",
  "HR Consultant",
  "Interior Designer",
  "Exterior Designer",
  "Landscape Designer",
  "Architect",
  "Civil Engineer",
  "Structural Engineer",
  "Mechanical Engineer",
  "Electrical Engineer",
  "Fashion Designer",
  "Makeup Artist",
  "Hair Stylist",
  "Fitness Trainer",
  "Nutritionist",
  "Life Coach",
  "Career Counselor",
  "Relationship Coach",
  "Online Tutor",
  "Language Tutor",
  "Music Tutor",
  "Math Tutor",
  "Science Tutor",
  "Art Tutor",
  "Dance Instructor",
  "Yoga Instructor",
  "Pilates Instructor",
  "Meditation Instructor",
  "Cooking Instructor",
  "Baking Instructor",
  "DIY Instructor",
  "Craft Instructor",
  "Gardening Instructor",
  "Photography Instructor",
  "Videography Instructor",
  "Graphic Design Instructor",
  "Web Development Instructor",
  "Programming Instructor",
  "Writing Instructor",
  "Marketing Instructor",
  "SEO Instructor",
  "Social Media Instructor",
  "Business Instructor",
  "Finance Instructor",
  "Accounting Instructor",
  "Legal Instructor",
  "Health Instructor",
  "Fitness Instructor",
  "Nutrition Instructor",
  "Lifestyle Instructor",
  "Career Instructor",
  "Relationship Instructor",
  "Parenting Instructor",
  "Education Instructor",
  "Language Instructor",
  "Music Instructor",
  "Art Instructor",
  "Craft Instructor",
  "Cooking Instructor",
  "Baking Instructor",
  "Beauty Instructor",
  "Fashion Instructor",
  "Photography Instructor",
  "Videography Instructor",
  "Technology Instructor",
  "Software Instructor",
  "App Development Instructor",
  "Game Development Instructor",
  "Coding Instructor",
  "Programming Instructor",
  "Database Instructor",
  "Web Development Instructor",
  "Graphic Design Instructor",
  "UI/UX Design Instructor",
  "Animation Instructor",
  "Video Editing Instructor",
  "Audio Editing Instructor",
  "Marketing Instructor",
  "Digital Marketing Instructor",
  "SEO Instructor",
  "Social Media Marketing Instructor",
  "Content Marketing Instructor",
  "Email Marketing Instructor",
  "Affiliate Marketing Instructor",
  "Influencer Marketing Instructor",
  "Video Marketing Instructor",
  "Podcasting Instructor",
  "Writing Instructor",
  "Content Writing Instructor",
  "Copywriting Instructor",
  "Editing Instructor",
  "Proofreading Instructor",
  "Ghostwriting Instructor",
  "Technical Writing Instructor",
  "Academic Writing Instructor",
  "Creative Writing Instructor",
  "Journalism Instructor",
  "Business Writing Instructor",
  "Legal Writing Instructor",
  "Medical Writing Instructor",
  "Finance Writing Instructor",
  "Resume Writing Instructor",
  "Cover Letter Writing Instructor",
  "Proposal Writing Instructor",
  "Grant Writing Instructor",
  "Scriptwriting Instructor",
  "Screenwriting Instructor",
  "Playwriting Instructor",
  "Speechwriting Instructor",
  "Marketing Writing Instructor",
  "Advertising Writing Instructor",
  "Public Relations Writing Instructor",
  "Media Writing Instructor",
  "Web Content Writing Instructor",
  "Blog Writing Instructor",
  "Article Writing Instructor",
  "Press Release Writing Instructor",
  "Social Media Writing Instructor",
  "Web Design Instructor",
  "Graphic Design Instructor",
  "Logo Design Instructor",
  "UI/UX Design Instructor",
  "Print Design Instructor",
  "Brand Identity Design Instructor",
  "Packaging Design Instructor",
  "Illustration Instructor",
  "Cartooning Instructor",
  "Animation Instructor",
  "Motion Graphics Instructor",
  "Digital Art Instructor",
  "Photography Instructor",
  "Portrait Photography Instructor",
  "Landscape Photography Instructor",
  "Product Photography Instructor",
  "Event Photography Instructor",
  "Fashion Photography Instructor",
  "Wedding Photography Instructor",
  "Street Photography Instructor",
  "Food Photography Instructor",
  "Real Estate Photography Instructor",
  "Travel Photography Instructor",
  "Nature Photography Instructor",
  "Wildlife Photography Instructor",
  "Documentary Photography Instructor",
  "Night Photography Instructor",
  "Astrophotography Instructor",
  "Fine Art Photography Instructor",
  "Black and White Photography Instructor",
  "Color Photography Instructor",
  "Digital Photography Instructor",
  "Film Photography Instructor",
  "Darkroom Photography Instructor",
  "Mobile Photography Instructor",
  "Video Production Instructor",
  "Scriptwriting Instructor",
  "Storyboarding Instructor",
  "Cinematography Instructor",
  "Camera Operation Instructor",
  "Lighting Instructor",
  "Sound Design Instructor",
  "Video Editing Instructor",
  "Color Grading Instructor",
  "Visual Effects (VFX) Instructor",
  "Motion Graphics Instructor",
  "Animation Instructor",
  "3D Animation Instructor",
  "2D Animation Instructor",
  "Stop Motion Animation Instructor",
  "Typography Instructor",
  "Kinetic Typography Instructor",
  "Hand Lettering Instructor",
  "Calligraphy Instructor",
  "Sign Painting Instructor",
  "Graffiti Art Instructor",
  "Stencil Art Instructor",
  "Street Art Instructor",
  "Mural Art Instructor",
  "Printmaking Instructor",
  "Drawing Instructor",
  "Painting Instructor",
  "Watercolor Painting Instructor",
  "Oil Painting Instructor",
  "Acrylic Painting Instructor",
  "Gouache Painting Instructor",
  "Pastel Painting Instructor",
  "Charcoal Drawing Instructor",
  "Pen and Ink Drawing Instructor",
  "Pencil Drawing Instructor",
  "Color Pencil Drawing Instructor",
  "Digital Painting Instructor",
  "Mixed Media Instructor",
  "Collage Instructor",
  "Sculpture Instructor",
  "Ceramics Instructor",
  "Pottery Instructor",
  "Glassblowing Instructor",
  "Metalworking Instructor",
  "Woodworking Instructor",
  "Jewelry Making Instructor",
  "Furniture Making Instructor",
  "Textile Arts Instructor",
  "Weaving Instructor",
  "Knitting Instructor",
  "Crochet Instructor",
  "Embroidery Instructor",
  "Quilting Instructor",
  "Sewing Instructor",
  "Fashion Design Instructor",
  "Pattern Making Instructor",
  "Draping Instructor",
  "Tailoring Instructor",
  "Fashion Illustration Instructor",
  "Accessory Design Instructor",
  "Shoe Design Instructor",
  "Bag Design Instructor",
  "Costume Design Instructor",
  "Textile Design Instructor",
  "Surface Pattern Design Instructor",
  "Print Design Instructor",
  "Fabric Painting Instructor",
  "Digital Fabric Design Instructor",
  "Pattern Design Instructor",
  "Interior Design Instructor",
  "Residential Interior Design Instructor",
  "Commercial Interior Design Instructor",
  "Hospitality Interior Design Instructor",
  "Retail Interior Design Instructor",
  "Office Interior Design Instructor",
  "Healthcare Interior Design Instructor",
  "Institutional Interior Design Instructor",
  "Educational Interior Design Instructor",
  "Kitchen Design Instructor",
  "Bathroom Design Instructor",
  "Living Room Design Instructor",
  "Bedroom Design Instructor",
  "Dining Room Design Instructor",
  "Home Office Design Instructor",
  "Closet Design Instructor",
  "Laundry Room Design Instructor",
  "Basement Design Instructor",
  "Attic Design Instructor",
  "Outdoor Space Design Instructor",
  "Landscape Design Instructor",
  "Residential Landscape Design Instructor",
  "Commercial Landscape Design Instructor",
  "Garden Design Instructor",
  "Backyard Design Instructor",
  "Patio Design Instructor",
  "Deck Design Instructor",
  "Porch Design Instructor",
  "Terrace Design Instructor",
  "Outdoor Kitchen Design Instructor",
  "Pool Design Instructor",
  "Spa Design Instructor",
  "Pond Design Instructor",
  "Water Feature Design Instructor",
  "Pathway Design Instructor",
  "Driveway Design Instructor",
  "Entryway Design Instructor",
  "Gate Design Instructor",
  "Fence Design Instructor",
  "Retaining Wall Design Instructor",
  "Hardscape Design Instructor",
  "Softscape Design Instructor",
  "Xeriscape Design Instructor",
  "Sustainable Landscape Design Instructor",
  "Organic Gardening Instructor",
  "Permaculture Design Instructor",
  "Edible Landscape Design Instructor",
  "Wildlife Garden Design Instructor",
  "Herb Garden Design Instructor",
  "Vegetable Garden Design Instructor",
  "Fruit Garden Design Instructor",
  "Flower Garden Design Instructor",
  "Rose Garden Design Instructor",
  "Japanese Garden Design Instructor",
  "English Garden Design Instructor",
  "French Garden Design Instructor",
  "Italian Garden Design Instructor",
  "Spanish Garden Design Instructor",
  "Mediterranean Garden Design Instructor",
  "Tropical Garden Design Instructor",
  "Desert Garden Design Instructor",
  "Mountain Garden Design Instructor",
  "Beach Garden Design Instructor",
  "Coastal Garden Design Instructor",
  "Waterfront Garden Design Instructor",
  "City Garden Design Instructor",
  "Balcony Garden Design Instructor",
  "Terrace Garden Design Instructor",
  "Roof Garden Design Instructor",
  "Vertical Garden Design Instructor",
  "Community Garden Design Instructor",
  "School Garden Design Instructor",
  "Park Design Instructor",
  "Recreational Area Design Instructor",
  "Outdoor Classroom Design Instructor",
  "Playground Design Instructor",
  "Sports Field Design Instructor",
  "Nature Trail Design Instructor",
  "Botanical Garden Design Instructor",
  "Zoo Design Instructor",
  "Aquarium Design Instructor",
  "Theme Park Design Instructor",
  "Golf Course Design Instructor",
  "Cemetery Design Instructor",
  "Memorial Garden Design Instructor",
  "Greenhouse Design Instructor",
  "Conservatory Design Instructor",
  "Orangery Design Instructor",
  "Sunroom Design Instructor",
  "Solarium Design Instructor",
  "Atrium Design Instructor",
  "Winter Garden Design Instructor",
  "Courtyard Design Instructor",
  "Piazza Design Instructor",
  "Plaza Design Instructor",
  "Square Design Instructor",
  "Circle Design Instructor",
  "Market Design Instructor",
  "Gathering Space Design Instructor",
  "Event Space Design Instructor",
  "Public Space Design Instructor",
  "Private Space Design Instructor",
  "Personal Garden Design Instructor",
  "Commercial Garden Design Instructor",
  "Industrial Garden Design Instructor",
  "Public Garden Design Instructor",
  "Institutional Garden Design Instructor",
  "Historical Garden Design Instructor",
  "Modern Garden Design Instructor",
  "Contemporary Garden Design Instructor",
  "Traditional Garden Design Instructor",
  "Minimalist Garden Design Instructor",
  "Eclectic Garden Design Instructor",
  "Urban Garden Design Instructor",
  "Suburban Garden Design Instructor",
  "Rural Garden Design Instructor",
  "Wild Garden Design Instructor",
  "Formal Garden Design Instructor",
  "Informal Garden Design Instructor",
  "Symmetrical Garden Design Instructor",
  "Asymmetrical Garden Design Instructor",
  "Geometric Garden Design Instructor",
  "Organic Garden Design Instructor",
  "Linear Garden Design Instructor",
  "Curved Garden Design Instructor",
  "Angular Garden Design Instructor",
  "Fluid Garden Design Instructor",
  "Structured Garden Design Instructor",
  "Freeform Garden Design Instructor",
  "Minimalist Landscape Design Instructor",
  "Formal Landscape Design Instructor",
  "Informal Landscape Design Instructor",
  "Naturalistic Landscape Design Instructor",
  "Abstract Landscape Design Instructor",
  "Sculptural Landscape Design Instructor",
  "Sensory Landscape Design Instructor",
  "Interactive Landscape Design Instructor",
  "Therapeutic Landscape Design Instructor",
  "Healing Garden Design Instructor",
  "Meditation Garden Design Instructor",
  "Peace Garden Design Instructor",
  "Spiritual Garden Design Instructor",
  "Zen Garden Design Instructor",
  "Mindfulness Garden Design Instructor",
  "Relaxation Garden Design Instructor",
  "Feng Shui Garden Design Instructor",
  "Wellness Garden Design Instructor",
  "Tranquility Garden Design Instructor",
  "Calming Garden Design Instructor",
  "Serene Garden Design Instructor",
  "Quiet Garden Design Instructor",
  "Private Garden Design Instructor",
  "Secluded Garden Design Instructor",
  "Intimate Garden Design Instructor",
  "Secret Garden Design Instructor",
  "Hidden Garden Design Instructor",
  "Enclosed Garden Design Instructor",
  "Sheltered Garden Design Instructor",
  "Personal Sanctuary Design Instructor",
  "Retreat Garden Design Instructor",
  "Refuge Garden Design Instructor",
  "Oasis Garden Design Instructor",
  "Haven Garden Design Instructor",
  "Escape Garden Design Instructor",
  "Sustainable Garden Design Instructor",
  "Eco-Friendly Garden Design Instructor",
  "Green Garden Design Instructor",
  "Environmentally Friendly Garden Design Instructor",
  "Low-Maintenance Garden Design Instructor",
  "Drought-Tolerant Garden Design Instructor",
  "Water-Wise Garden Design Instructor",
  "Native Garden Design Instructor",
  "Wildlife-Friendly Garden Design Instructor",
  "Pollinator-Friendly Garden Design Instructor",
  "Butterfly Garden Design Instructor",
  "Bird-Friendly Garden Design Instructor",
  "Bat-Friendly Garden Design Instructor",
  "Bee-Friendly Garden Design Instructor",
  "Hummingbird Garden Design Instructor",
  "Rooftop Garden Design Instructor",
  "Balcony Garden Design Instructor",
  "Terrace Garden Design Instructor",
  "Deck Garden Design Instructor",
  "Patio Garden Design Instructor",
  "Container Garden Design Instructor",
  "Vertical Garden Design Instructor",
  "Hanging Garden Design Instructor",
  "Wall Garden Design Instructor",
  "Fence Garden Design Instructor",
  "Window Box Garden Design Instructor",
  "Raised Bed Garden Design Instructor",
  "Planter Box Garden Design Instructor",
  "Pot Garden Design Instructor",
  "Pallet Garden Design Instructor",
  "Hydroponic Garden Design Instructor",
  "Aquaponic Garden Design Instructor",
  "Terrarium Garden Design Instructor",
  "Vivarium Garden Design Instructor",
  "Atrium Garden Design Instructor",
  "Courtyard Garden Design Instructor",
  "Public Garden Design Instructor",
  "Community Garden Design Instructor",
  "School Garden Design Instructor",
  "Park Garden Design Instructor",
  "Urban Garden Design Instructor",
  "Suburban Garden Design Instructor",
  "Rural Garden Design Instructor",
  "Historical Garden Design Instructor",
  "Modern Garden Design Instructor",
  "Contemporary Garden Design Instructor",
  "Traditional Garden Design Instructor",
  "Minimalist Garden Design Instructor",
  "Formal Garden Design Instructor",
  "Informal Garden Design Instructor",
  "Coastal Garden Design Instructor",
  "Desert Garden Design Instructor",
  "Mountain Garden Design Instructor",
  "Woodland Garden Design Instructor",
  "Tropical Garden Design Instructor",
  "Mediterranean Garden Design Instructor",
  "Asian Garden Design Instructor",
  "European Garden Design Instructor",
  "English Garden Design Instructor",
  "French Garden Design Instructor",
  "Italian Garden Design Instructor",
  "Spanish Garden Design Instructor",
  "Japanese Garden Design Instructor",
  "Chinese Garden Design Instructor",
  "Korean Garden Design Instructor",
  "Thai Garden Design Instructor",
  "Indonesian Garden Design Instructor",
  "Philippine Garden Design Instructor",
  "Vietnamese Garden Design Instructor",
  "Indian Garden Design Instructor",
  "Persian Garden Design Instructor",
  "Islamic Garden Design Instructor",
  "African Garden Design Instructor",
  "Australian Garden Design Instructor",
  "New Zealand Garden Design Instructor",
  "Canadian Garden Design Instructor",
  "American Garden Design Instructor",
  "Mexican Garden Design Instructor",
  "Native American Garden Design Instructor",
  "South American Garden Design Instructor",
  "Brazilian Garden Design Instructor",
  "Argentinian Garden Design Instructor",
  "Chilean Garden Design Instructor",
  "Colombian Garden Design Instructor",
  "Peruvian Garden Design Instructor",
  "Ecuadorian Garden Design Instructor",
  "Venezuelan Garden Design Instructor",
  "Central American Garden Design Instructor",
  "Costa Rican Garden Design Instructor",
  "Panamanian Garden Design Instructor",
  "Belizean Garden Design Instructor",
  "Guatemalan Garden Design Instructor",
  "Honduran Garden Design Instructor",
  "Nicaraguan Garden Design Instructor",
  "Salvadoran Garden Design Instructor",
  "Caribbean Garden Design Instructor",
  "Cuban Garden Design Instructor",
  "Haitian Garden Design Instructor",
  "Jamaican Garden Design Instructor",
  "Bahamian Garden Design Instructor",
  "Barbadian Garden Design Instructor",
  "Trinidadian Garden Design Instructor",
  "Grenadian Garden Design Instructor",
  "Guyanese Garden Design Instructor",
  "Surinamese Garden Design Instructor",
  "French Guianese Garden Design Instructor",
  "Puerto Rican Garden Design Instructor",
  "Virgin Islander Garden Design Instructor",
  "British Virgin Islander Garden Design Instructor",
  "American Virgin Islander Garden Design Instructor",
  "Dutch Caribbean Garden Design Instructor",
  "Aruban Garden Design Instructor",
  "Bonairean Garden Design Instructor",
  "Curaçaoan Garden Design Instructor",
  "Sabaean Garden Design Instructor",
  "Sint Eustatian Garden Design Instructor",
  "Sint Maartenian Garden Design Instructor",
  "Saint Martiner Garden Design Instructor",
  "Sint Maartener Garden Design Instructor",
  "Saint Martinian Garden Design Instructor",
];

export const required_skills = [
  "HTML5",
  "CSS3",
  "JavaScript",
  "TypeScript",
  "React.js",
  "Angular",
  "Vue.js",
  "Node.js",
  "Express.js",
  "Django",
  "Flask",
  "Ruby on Rails",
  "Laravel",
  "Spring Boot",
  "ASP.NET",
  "C#",
  "Java",
  "Python",
  "PHP",
  "Go",
  "Scala",
  "Swift",
  "Kotlin",
  "C++",
  "Rust",
  "SQL",
  "NoSQL",
  "MongoDB",
  "Firebase",
  "AWS",
  "Azure",
  "Google Cloud Platform",
  "Docker",
  "Kubernetes",
  "Jenkins",
  "CircleCI",
  "GitLab CI/CD",
  "GitHub Actions",
  "UI/UX Design",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Sketch",
  "Figma",
  "InVision",
  "Zeplin",
  "Principle",
  "Axure RP",
  "Adobe XD",
  "Wireframing",
  "Prototyping",
  "User Research",
  "Usability Testing",
  "Visual Design",
  "Interaction Design",
  "Information Architecture",
  "Typography",
  "Logo Design",
  "Brand Identity",
  "Illustration",
  "Motion Graphics",
  "Adobe Premiere Pro",
  "Final Cut Pro",
  "DaVinci Resolve",
  "Adobe After Effects",
  "Blender",
  "Maya",
  "3ds Max",
  "Unity",
  "Unreal Engine",
  "Augmented Reality (AR)",
  "Virtual Reality (VR)",
  "Game Development",
  "UI/UX Animation",
  "Responsive Design",
  "Bootstrap",
  "Sass",
  "LESS",
  "Tailwind CSS",
  "GraphQL",
  "RESTful APIs",
  "Microservices Architecture",
  "Serverless Computing",
  "Blockchain Development",
  "Smart Contracts",
  "Cryptocurrency",
  "Ethereum",
  "Solidity",
  "Cybersecurity",
  "Ethical Hacking",
  "Penetration Testing",
  "Network Administration",
  "Linux Administration",
  "Windows Server Administration",
  "Shell Scripting",
  "DevOps",
  "Continuous Integration (CI)",
  "Continuous Deployment (CD)",
  "Infrastructure as Code (IaC)",
  "Configuration Management",
  "Monitoring Tools",
  "Ansible",
  "Terraform",
  "Puppet",
  "Chef",
  "SaltStack",
  "Data Science",
  "Machine Learning",
  "Deep Learning",
  "Natural Language Processing (NLP)",
  "Computer Vision",
  "Big Data",
  "Data Analytics",
  "Data Visualization",
  "Business Intelligence (BI)",
  "ETL (Extract, Transform, Load)",
  "Apache Hadoop",
  "Apache Spark",
  "Apache Flink",
  "Apache Kafka",
  "TensorFlow",
  "PyTorch",
  "Scikit-learn",
  "Pandas",
  "NumPy",
  "Matplotlib",
  "Tableau",
  "Power BI",
  "Microsoft Excel",
  "Google Sheets",
  "Technical Writing",
  "Content Writing",
  "Copywriting",
  "Blogging",
  "Search Engine Optimization (SEO)",
  "Social Media Marketing",
  "Email Marketing",
  "Pay-per-Click (PPC) Advertising",
  "Content Management Systems (CMS)",
  "WordPress",
  "Joomla",
  "Drupal",
  "Magento",
  "E-commerce Development",
  "Shopify",
  "WooCommerce",
  "Magento Commerce",
  "Payment Gateway Integration",
  "User Testing",
  "Quality Assurance (QA)",
  "Agile Methodology",
  "Scrum",
  "Kanban",
  "Lean Software Development",
  "Extreme Programming (XP)",
  "Test-Driven Development (TDD)",
  "Behavior-Driven Development (BDD)",
  "Pair Programming",
  "Code Review",
  "Software Development Life Cycle (SDLC)",
  "Version Control",
  "Git",
  "SVN",
  "Mercurial",
  "Team Foundation Version Control (TFVC)",
  "Bitbucket",
  "GitHub",
  "GitLab",
  "Project Management",
  "Product Management",
  "Leadership",
  "Communication",
  "Problem-Solving",
  "Critical Thinking",
  "Decision Making",
  "Time Management",
  "Conflict Resolution",
  "Emotional Intelligence",
  "Negotiation",
  "Stakeholder Management",
  "Teamwork",
  "Customer Service",
  "Client Management",
  "Presentation Skills",
  "Public Speaking",
  "Networking",
  "Financial Management",
  "Risk Management",
  "Contract Management",
  "Procurement",
  "Vendor Management",
  "Strategic Planning",
  "Market Research",
  "Competitive Analysis",
  "SWOT Analysis",
  "Feasibility Studies",
  "Business Modeling",
  "Business Process Improvement",
  "Change Management",
  "Project Budgeting",
  "Cost Estimation",
  "Resource Allocation",
  "Quality Management",
  "Performance Management",
  "Human Resource Management",
  "Recruitment",
  "Onboarding",
  "Training and Development",
  "Employee Relations",
  "Employee Engagement",
  "Performance Appraisal",
  "Compensation and Benefits",
  "HR Compliance",
  "Workforce Planning",
  "Organizational Development",
  "Succession Planning",
  "Talent Management",
  "Employee Wellness",
  "Workplace Diversity",
  "Labor Relations",
  "Health and Safety Management",
];

export const jobCategory = [
  { id: 1, label: "Web Developer", value: "Web Developer" },
  { id: 2, label: "Web Designer", value: "Web Designer" },
  { id: 3, label: "UI/UX Designer", value: "UI/UX Designer" },
  { id: 4, label: "Jamovi", value: "Jamovi" },
  { id: 5, label: ".NET", value: ".NET" },
  { id: 6, label: "3ds Max", value: "3ds Max" },
  { id: 7, label: "Ableton Live", value: "Ableton Live" },
  { id: 8, label: "Accounting", value: "Accounting" },
  { id: 9, label: "Acting Audition", value: "Acting Audition" },
  { id: 10, label: "Acting Technique", value: "Acting Technique" },
  { id: 11, label: "Adobe After Effects", value: "Adobe After Effects" },
  { id: 12, label: "Adobe Audition", value: "Adobe Audition" },
  { id: 13, label: "Adobe Creative Suite", value: "Adobe Creative Suite" },
  { id: 14, label: "Adobe Dreamweaver", value: "Adobe Dreamweaver" },
  { id: 15, label: "Adobe Fireworks", value: "Adobe Fireworks" },
  { id: 16, label: "Adobe Flash", value: "Adobe Flash" },
  { id: 17, label: "Adobe Illustrator", value: "Adobe Illustrator" },
  { id: 18, label: "Adobe InDesign", value: "Adobe InDesign" },
  { id: 19, label: "Adobe Photoshop", value: "Adobe Photoshop" },
  {
    id: 20,
    label: "Adobe Photoshop Lightroom CC",
    value: "Adobe Photoshop Lightroom CC",
  },
  { id: 21, label: "Adobe Premiere Pro", value: "Adobe Premiere Pro" },
  { id: 22, label: "Adobe XD", value: "Adobe XD" },
  { id: 23, label: "Advanced Excel", value: "Advanced Excel" },
  { id: 24, label: "AJAX", value: "AJAX" },
  { id: 25, label: "Algorithms", value: "Algorithms" },
  { id: 26, label: "Allegro Software", value: "Allegro Software" },
  {
    id: 27,
    label: "Amazon Web Server (AWS)",
    value: "Amazon Web Server (AWS)",
  },
  {
    id: 28,
    label: "Amazon Web Services (AWS)",
    value: "Amazon Web Services (AWS)",
  },
  { id: 29, label: "American English", value: "American English" },
  {
    id: 30,
    label: "Analog And Digital Circuits",
    value: "Analog And Digital Circuits",
  },
  { id: 31, label: "Anchoring", value: "Anchoring" },
  { id: 32, label: "Android", value: "Android" },
  { id: 33, label: "Angular 2.0", value: "Angular 2.0" },
  { id: 34, label: "Angular 7.0", value: "Angular 7.0" },
  { id: 35, label: "AngularJS", value: "AngularJS" },
  { id: 36, label: "Animation", value: "Animation" },
  { id: 37, label: "ANSA", value: "ANSA" },
  { id: 38, label: "Ansible", value: "Ansible" },
  { id: 39, label: "ANSYS", value: "ANSYS" },
  { id: 40, label: "Apache", value: "Apache" },
  { id: 41, label: "Apache Cassandra", value: "Apache Cassandra" },
  { id: 42, label: "Apache CloudStack", value: "Apache CloudStack" },
  { id: 43, label: "Apache Kafka", value: "Apache Kafka" },
  { id: 44, label: "Apex", value: "Apex" },
  { id: 45, label: "APIs", value: "APIs" },
  {
    id: 46,
    label: "Arabic Proficiency (Spoken)",
    value: "Arabic Proficiency (Spoken)",
  },
  {
    id: 47,
    label: "Arabic Proficiency (Written)",
    value: "Arabic Proficiency (Written)",
  },
  { id: 48, label: "ArcGIS", value: "ArcGIS" },
  { id: 49, label: "Arduino", value: "Arduino" },
  { id: 50, label: "ARM Microcontroller", value: "ARM Microcontroller" },
  { id: 51, label: "Articulate 360", value: "Articulate 360" },
  { id: 52, label: "Articulate Storyline", value: "Articulate Storyline" },
  {
    id: 53,
    label: "Artificial Intelligence (AI)",
    value: "Artificial Intelligence (AI)",
  },
  { id: 54, label: "ASP.NET", value: "ASP.NET" },
  {
    id: 55,
    label: "Assamese Proficiency (Spoken)",
    value: "Assamese Proficiency (Spoken)",
  },
  {
    id: 56,
    label: "Assamese Proficiency (Written)",
    value: "Assamese Proficiency (Written)",
  },
  { id: 57, label: "Atmel AVR", value: "Atmel AVR" },
  { id: 58, label: "Audacity", value: "Audacity" },
  { id: 59, label: "Audio Editing", value: "Audio Editing" },
  { id: 60, label: "Audio Production", value: "Audio Production" },
  { id: 61, label: "Audiology", value: "Audiology" },
  { id: 62, label: "AutoCAD", value: "AutoCAD" },
  { id: 63, label: "Autodesk 123D Design", value: "Autodesk 123D Design" },
  { id: 64, label: "Autodesk Alias", value: "Autodesk Alias" },
  { id: 65, label: "Autodesk CFD", value: "Autodesk CFD" },
  { id: 66, label: "Autodesk Fusion 360", value: "Autodesk Fusion 360" },
  { id: 67, label: "Autodesk Inventor", value: "Autodesk Inventor" },
  { id: 68, label: "Autodesk Maya", value: "Autodesk Maya" },
  { id: 69, label: "Autodesk Moldflow", value: "Autodesk Moldflow" },
  { id: 70, label: "Autodesk Mudbox", value: "Autodesk Mudbox" },
  { id: 71, label: "Autodesk Revit", value: "Autodesk Revit" },
  { id: 72, label: "Autodesk SketchBook", value: "Autodesk SketchBook" },
  { id: 73, label: "Backbone.js", value: "Backbone.js" },
  { id: 74, label: "Bar Bending Schedule", value: "Bar Bending Schedule" },
  { id: 75, label: "Bash Scripting", value: "Bash Scripting" },
  {
    id: 76,
    label: "Bengali Proficiency (Spoken)",
    value: "Bengali Proficiency (Spoken)",
  },
  {
    id: 77,
    label: "Bengali Proficiency (Written)",
    value: "Bengali Proficiency (Written)",
  },
  { id: 78, label: "Big Data", value: "Big Data" },
  {
    id: 79,
    label: "BIM (Building Information Modeling)",
    value: "BIM (Building Information Modeling)",
  },
  { id: 80, label: "Bioinformatics", value: "Bioinformatics" },
  { id: 81, label: "Biology", value: "Biology" },
  { id: 82, label: "Biostatistics", value: "Biostatistics" },
  { id: 83, label: "Blender 3D", value: "Blender 3D" },
  { id: 84, label: "Blockchain", value: "Blockchain" },
  { id: 85, label: "Blogging", value: "Blogging" },
  {
    id: 86,
    label: "BMS (Building Management System)",
    value: "BMS (Building Management System)",
  },
  {
    id: 87,
    label: "Bodo Proficiency (Spoken)",
    value: "Bodo Proficiency (Spoken)",
  },
  {
    id: 88,
    label: "Bodo Proficiency (Written)",
    value: "Bodo Proficiency (Written)",
  },
  { id: 89, label: "Bootstrap", value: "Bootstrap" },
  { id: 90, label: "British English", value: "British English" },
  { id: 91, label: "Business Analysis", value: "Business Analysis" },
  { id: 92, label: "Business Research", value: "Business Research" },
  { id: 93, label: "C Programming", value: "C Programming" },
  { id: 94, label: "C#", value: "C#" },
  { id: 95, label: "C#.NET", value: "C#.NET" },
  { id: 96, label: "C++ Programming", value: "C++ Programming" },
  { id: 97, label: "CAD Design", value: "CAD Design" },
  { id: 98, label: "CakePHP", value: "CakePHP" },
  { id: 99, label: "Calligraphy", value: "Calligraphy" },
  {
    id: 100,
    label: "CAM (Computer-Aided Manufacturing)",
    value: "CAM (Computer-Aided Manufacturing)",
  },
  { id: 101, label: "Canva", value: "Canva" },
  {
    id: 102,
    label: "Catalyst MVC Web Framework",
    value: "Catalyst MVC Web Framework",
  },
  { id: 103, label: "Catia", value: "Catia" },
  {
    id: 104,
    label: "CCNA (Cisco Certified Network Associate)",
    value: "CCNA (Cisco Certified Network Associate)",
  },
  { id: 105, label: "Chemistry", value: "Chemistry" },
  {
    id: 106,
    label: "Chinese Proficiency (Spoken)",
    value: "Chinese Proficiency (Spoken)",
  },
  {
    id: 107,
    label: "Chinese Proficiency (Written)",
    value: "Chinese Proficiency (Written)",
  },
  { id: 108, label: "Cinema 4D", value: "Cinema 4D" },
  { id: 109, label: "Civil Engineering", value: "Civil Engineering" },
  { id: 110, label: "Clean Energy", value: "Clean Energy" },
  { id: 111, label: "Clip Studio Paint", value: "Clip Studio Paint" },
  { id: 112, label: "Clojure", value: "Clojure" },
  { id: 113, label: "Cloud Computing", value: "Cloud Computing" },
  {
    id: 114,
    label: "CMS (Content Management System)",
    value: "CMS (Content Management System)",
  },
  { id: 115, label: "COBOL", value: "COBOL" },
  { id: 116, label: "CodeIgniter", value: "CodeIgniter" },
  { id: 117, label: "Communication Skills", value: "Communication Skills" },
  {
    id: 118,
    label: "Compensation and Benefits",
    value: "Compensation and Benefits",
  },
  { id: 119, label: "Compiler Design", value: "Compiler Design" },
  { id: 120, label: "Computer Basics", value: "Computer Basics" },
];

export const experience_levels = [
  "Fresher",
  "Intern",
  "Entry Level",
  "Junior",
  "Associate",
  "1 Year",
  "2 Years",
  "3 Years",
  "Mid-Level",
  "4 Years",
  "5 Years",
  "Senior",
  "Lead",
  "6 Years",
  "7 Years",
  "8 Years",
  "Principal",
  "9 Years",
  "10+ Years",
  "Expert",
  "Veteran",
  "Guru",
  "Master",
  "Ninja",
  "Wizard",
];

export const jobType = [
  { id: 1, label: "Full Time", value: "full time" },
  { id: 2, label: "Part Time", value: "part time" },
  { id: 2, label: "Contract", value: "contract" },
  { id: 3, label: "Temporary", value: "temporary" },
  { id: 4, label: "Internship", value: "internship" },
  { id: 5, label: "Volunteer", value: "volunteer" },
];

export const duration = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11];

export const moneySymbols = [
  { id: 1, symbols: "₹", value: "₹" },
  { id: 1, symbols: "$", value: "$" },
  { id: 1, symbols: "€", value: "€" },
  { id: 1, symbols: "£", value: "£" },
  { id: 1, symbols: "CHF", value: "CHF" },
  { id: 1, symbols: "SGD", value: "SGD" },
  { id: 1, symbols: "Yen", value: "Yen" },
  { id: 1, symbols: "NIS", value: "NIS" },
  { id: 1, symbols: "¥", value: "¥" },
  { id: 1, symbols: "AED", value: "AED" },
  { id: 1, symbols: "LKR", value: "LKR" },
];

export const perksData = [
  { id: 1, perks: "Certificate", value: "certificate" },
  { id: 1, perks: "Flexible work hours", value: "flexible work hours" },
  { id: 1, perks: "Informal dress code", value: "informal dress code" },
  {
    id: 1,
    perks: "Letter of recommendation",
    value: "letter of recommendation",
  },
  { id: 1, perks: "5 days a week", value: "5 days a week" },
  { id: 1, perks: "Free snacks & beverages", value: "free snacks & beverages" },
];

export const candidatesDataSchema = [
  {
    name: "Wade Warren",
    title: "Developer",
    location: "London, UK",
    hourly_rate: "$99",
    member_since: "Aug 19, 2020",
    services: ["App", "Design", "Digital"],
    experience_range: "0-2 Years",
    age_range: "28-33 Years",
    current_salary_range: "11K - 15K",
    expected_salary_range: "26K - 30K",
    gender: "Female",
    languages: ["English", "German", "Spanish"],
    education_level: "Master Degree",
    social_media: ["Facebook", "Twitter", "Instagram", "LinkedIn"],
    professional_skills: [
      "App",
      "Administrative",
      "Android",
      "WordPress",
      "Design",
      "React",
    ],
    education: [
      {
        degree: "Bachelors in Fine Arts",
        university: "Modern College",
        years_attended: "2012 - 2014",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a ipsum tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
      },
      {
        degree: "Computer Science",
        university: "Harvard University",
        years_attended: "2008 - 2012",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a ipsum tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
      },
    ],
    work_experience: [
      {
        position: "Product Designer",
        company: "Spotify Inc.",
        years_worked: "2008 - 2012",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a ipsum tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
      },
      {
        position: "Sr UX Engineer",
        company: "Dropbox Inc.",
        years_worked: "2012 - 2014",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a ipsum tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
      },
    ],
    awards: [
      {
        award: "Perfect Attendance Programs",
        category: "Software Algorithm",
        years: "2008 - 2014",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a ipsum tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
      },
      {
        award: "Top Performer Recognition",
        category: "Web Application",
        years: "2012 - 2014",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a ipsum tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
      },
    ],
    about:
      "I am a passionate developer with a strong background in app development, design, and digital technologies. I am dedicated to delivering high-quality solutions and constantly learning and adapting to new technologies and methodologies.",
    image_url: "https://example.com/profile_image.jpg",
    availability: "Available for freelance projects",
    contact_info: {
      email: "wade@example.com",
      phone: "+1234567890",
      website: "https://wadewarren.com",
    },
    location_preference: ["London", "Berlin", "Barcelona"],
    portfolio: [
      {
        project_name: "AppX",
        description:
          "Developed a cutting-edge mobile application for seamless user experience.",
        technologies_used: ["React Native", "Firebase"],
        year: 2021,
      },
      {
        project_name: "DesignHub",
        description:
          "Led the design team in creating visually stunning interfaces for web and mobile platforms.",
        technologies_used: ["Adobe XD", "Sketch"],
        year: 2020,
      },
    ],
  },
  {
    name: "Wade Warren",
    title: "Developer",
    location: "London, UK",
    hourly_rate: "$99",
    member_since: "Aug 19, 2020",
    services: ["App", "Design", "Digital"],
    experience_range: "0-2 Years",
    age_range: "28-33 Years",
    current_salary_range: "11K - 15K",
    expected_salary_range: "26K - 30K",
    gender: "Female",
    languages: ["English", "German", "Spanish"],
    education_level: "Master Degree",
    social_media: ["Facebook", "Twitter", "Instagram", "LinkedIn"],
    professional_skills: [
      "App",
      "Administrative",
      "Android",
      "WordPress",
      "Design",
      "React",
    ],
    education: [
      {
        degree: "Bachelors in Fine Arts",
        university: "Modern College",
        years_attended: "2012 - 2014",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a ipsum tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
      },
      {
        degree: "Computer Science",
        university: "Harvard University",
        years_attended: "2008 - 2012",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a ipsum tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
      },
    ],
    work_experience: [
      {
        position: "Product Designer",
        company: "Spotify Inc.",
        years_worked: "2008 - 2012",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a ipsum tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
      },
      {
        position: "Sr UX Engineer",
        company: "Dropbox Inc.",
        years_worked: "2012 - 2014",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a ipsum tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
      },
    ],
    awards: [
      {
        award: "Perfect Attendance Programs",
        category: "Software Algorithm",
        years: "2008 - 2014",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a ipsum tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
      },
      {
        award: "Top Performer Recognition",
        category: "Web Application",
        years: "2012 - 2014",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a ipsum tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
      },
    ],
    about:
      "I am a passionate developer with a strong background in app development, design, and digital technologies. I am dedicated to delivering high-quality solutions and constantly learning and adapting to new technologies and methodologies.",
    image_url: "https://example.com/profile_image.jpg",
    availability: "Available for freelance projects",
    contact_info: {
      email: "wade@example.com",
      phone: "+1234567890",
      website: "https://wadewarren.com",
    },
    location_preference: ["London", "Berlin", "Barcelona"],
    portfolio: [
      {
        project_name: "AppX",
        description:
          "Developed a cutting-edge mobile application for seamless user experience.",
        technologies_used: ["React Native", "Firebase"],
        year: 2021,
      },
      {
        project_name: "DesignHub",
        description:
          "Led the design team in creating visually stunning interfaces for web and mobile platforms.",
        technologies_used: ["Adobe XD", "Sketch"],
        year: 2020,
      },
    ],
  },
];

export const resumeAlert = [
  {
    title: "Education",
    alert_query:
      "Category: Education Training, Posted Date: All, Salary: $1000 – $3000",
    number_jobs: 5,
    times: "Weekly",
    actions: [
      {
        candidate_name: "John Doe",
        job_title: "Mathematics Teacher",
        company: "ABC School",
        location: "City, Country",
        salary: "$2500 per month",
        posted_date: "February 1, 2024",
        candidate_about:
          "Experienced mathematics teacher with a passion for helping students understand complex concepts and excel in their studies.",
        candidate_skills: ["Mathematics", "Teaching", "Curriculum Development"],
        candidate_experience: "5 years",
        candidate_education: "Bachelor's Degree in Mathematics",
        candidate_languages: ["English"],
        candidate_contact: {
          email: "john.doe@example.com",
          phone: "+1234567890",
          linkedin: "linkedin.com/in/johndoe",
        },
      },
      {
        candidate_name: "Jane Smith",
        job_title: "English Tutor",
        company: "Language Institute",
        location: "City, Country",
        salary: "$2000 per month",
        posted_date: "February 3, 2024",
        candidate_about:
          "Passionate English tutor with a focus on improving students' language skills through interactive lessons and engaging activities.",
        candidate_skills: [
          "English Language",
          "Teaching",
          "Language Proficiency Assessment",
        ],
        candidate_experience: "3 years",
        candidate_education: "Master's Degree in English Literature",
        candidate_languages: ["English", "Spanish"],
        candidate_contact: {
          email: "jane.smith@example.com",
          phone: "+1234567890",
          linkedin: "linkedin.com/in/janesmith",
        },
      },
      {
        candidate_name: "David Johnson",
        job_title: "School Counselor",
        company: "XYZ Academy",
        location: "City, Country",
        salary: "$2800 per month",
        posted_date: "February 5, 2024",
        candidate_about:
          "Dedicated school counselor committed to supporting students' social, emotional, and academic growth to help them reach their full potential.",
        candidate_skills: [
          "Counseling",
          "Student Support Services",
          "Mental Health Awareness",
        ],
        candidate_experience: "7 years",
        candidate_education: "Master's Degree in Counseling Psychology",
        candidate_languages: ["English", "French"],
        candidate_contact: {
          email: "david.johnson@example.com",
          phone: "+1234567890",
          linkedin: "linkedin.com/in/davidjohnson",
        },
      },
      {
        candidate_name: "Emily Brown",
        job_title: "Physics Lecturer",
        company: "University of Science",
        location: "City, Country",
        salary: "$3000 per month",
        posted_date: "February 7, 2024",
        candidate_about:
          "Dynamic physics lecturer with a passion for making complex scientific concepts accessible to students through engaging lectures and hands-on experiments.",
        candidate_skills: ["Physics", "Lecturing", "Laboratory Instruction"],
        candidate_experience: "10 years",
        candidate_education: "Ph.D. in Physics",
        candidate_languages: ["English", "German"],
        candidate_contact: {
          email: "emily.brown@example.com",
          phone: "+1234567890",
          linkedin: "linkedin.com/in/emilybrown",
        },
      },
      {
        candidate_name: "Michael Taylor",
        job_title: "Art Instructor",
        company: "Community College",
        location: "City, Country",
        salary: "$2200 per month",
        posted_date: "February 9, 2024",
        candidate_about:
          "Creative and enthusiastic art instructor dedicated to fostering students' creativity and artistic expression through various mediums and techniques.",
        candidate_skills: ["Art Instruction", "Visual Arts", "Mixed Media"],
        candidate_experience: "4 years",
        candidate_education: "Bachelor's Degree in Fine Arts",
        candidate_languages: ["English"],
        candidate_contact: {
          email: "michael.taylor@example.com",
          phone: "+1234567890",
          linkedin: "linkedin.com/in/michaeltaylor",
        },
      },
    ],
  },
];

export let countryList = [
  "China",
  "India",
  "United States",
  "Indonesia",
  "Brazil",
  "Nigeria",
  "Japan",
  "Russia",
  "Bangladesh",
  "Mexico",
  "Germany",
  "Philippines",
  "Turkey",
  "Vietnam",
  "United Kingdom",
  "Iran",
  "France",
  "Thailand",
  "Italy",
  "Egypt",
];

export let onboarding_experience = [
  "< 1 Year",
  "1 Year",
  "2 Years",
  "3 Years",
  "4 Years",
  "5 Years",
  "6 Years",
  "7 Years",
  "8 Years",
  "9 Years",
  "10+ Years",
];

export const currencies = [
  { name: "United States Dollar", symbol: "$" },
  { name: "Euro", symbol: "€" },
  { name: "British Pound", symbol: "£" },
  { name: "Japanese Yen", symbol: "¥" },
  { name: "Canadian Dollar", symbol: "C$" },
  { name: "Australian Dollar", symbol: "A$" },
  { name: "Swiss Franc", symbol: "CHF" },
  { name: "Chinese Yuan", symbol: "¥" },
  { name: "Swedish Krona", symbol: "kr" },
  { name: "New Zealand Dollar", symbol: "NZ$" },
  { name: "Mexican Peso", symbol: "Mex$" },
  { name: "Singapore Dollar", symbol: "S$" },
  { name: "Hong Kong Dollar", symbol: "HK$" },
  { name: "Norwegian Krone", symbol: "kr" },
  { name: "South Korean Won", symbol: "₩" },
  { name: "Russian Ruble", symbol: "₽" },
  { name: "Indian Rupee", symbol: "₹" },
  { name: "Brazilian Real", symbol: "R$" },
  { name: "South African Rand", symbol: "R" },
  { name: "Ukrainian Hryvnia", symbol: "₴" },
];

export const most_important_next_job = [
  "Having a say in what I work on and how I work",
  "Opportunities to progress within the company",
  "Team members I can learn from",
  "A company with a good growth trajectory",
  "Mentorship opportunities",
  "Learn new things and develop my skills",
  "Challenging problems to work on",
  "A diverse team",
];

export const flexible_remote_work_policy = [
  "Very important",
  "Important",
  "Not important",
];
